# Generated by Django 3.2.8 on 2021-10-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_tags'),
        ('input', '0002_alter_input_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Produto'),
        ),
    ]
