# Generated by Django 3.2.8 on 2021-10-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_alter_input_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='prince',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
