# Generated by Django 3.2.8 on 2021-10-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_input_prince'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='prince',
            new_name='price',
        ),
    ]
