# version of docker-compose syntax
version: '3.7'

services:
  db:
    image: postgres:12.5
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - production_db_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - production_static_data:/vol/web
    restart: always
    env_file:
      - .env
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - production_static_data:/vol/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  production_static_data:
    external: true
  production_db_volume:
    external: true
