# version of docker-compose syntax
version: '3.7'

services:
  db:
    image: postgres:12.5
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - development_db_volume:/var/lib/postgresql/data/
    env_file:
      - .env
  
  app:
    build: .
    restart: always
    volumes:
      - ./src:/app
    depends_on:
      - db
    ports:
      - "80:8000"
    env_file: .env
    entrypoint:
      - ./../scripts/entrypoint.dev.sh

volumes:
  development_db_volume:
