# Generated by Django 3.2.8 on 2021-12-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_sizes_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('size', 'product')},
        ),
    ]
