# Generated by Django 3.2.8 on 2021-10-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0003_alter_output_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
