# Generated by Django 3.2.8 on 2021-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0004_output_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='amount',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='output',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço'),
        ),
    ]
