# Generated by Django 3.2.8 on 2021-10-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='invetory',
        ),
    ]
