# Generated by Django 3.2.8 on 2021-10-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('product', '0015_auto_20211011_0109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='Tags'),
        ),
    ]
