# Generated by Django 3.2.8 on 2022-01-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_size_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Roupas'), (2, 'Calçados'), (3, 'Acessórios')], default=1, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Unissex')], verbose_name='Sexo'),
        ),
    ]
