# Generated by Django 3.2.8 on 2022-01-24 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_size_product'),
        ('transaction', '0003_auto_20220124_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.size', verbose_name='Tamanho'),
        ),
    ]
